#!/bin/bash

for i in 166.111.8.238 \
    0.0.0.0            \
    255.255.255.255    \
    125.34.171.190     \
    59.66.122.23       \
    123.118.3.1        \
    192.168.1.1        \
    10.0.1.2 
do
    echo -n $i ", " 
    ./ip_seek $i ~/etc/QQWry.dat | iconv -f gbk -t utf8 
done
